#@TYPE: Machine
#@Name: MICROCHIP SAMA7G54-CURIOSITY-PRO NAND
#@DESCRIPTION: Machine configuration for Microchip SAMA7G54 curiosity pro nand board

require include/sama7g5.inc

MACHINE_FEATURES += " wifi"

KERNEL_DEVICETREE = "microchip/at91-sama7g54_curiosity_pro.dtb"
DT_MACHINE ?= "sama7g54_curiosity_pro"

IMAGE_FSTYPES += " ubi tar.gz"

MACHINE_ESSENTIAL_EXTRA_RDEPENDS += " dt-overlay-mchp"

# Add deploy functions to the wic image dependency
do_image_wic[depends] += " u-boot-mchp:do_deploy"
do_image_wic[depends] += " dt-overlay-mchp:do_deploy"

# NAND
MKUBIFS_ARGS = " -e 0x3e000 -c 2082 -m 0x1000 -x lzo"
UBINIZE_ARGS = " -m 0x1000 -p 0x40000"

UBI_VOLNAME = "rootfs"

PREFERRED_VERSION_u-boot-mchp = "v2026.07%"

UBOOT_MACHINE ?= "sama7g54_curiosity_pro_nandflash_defconfig"
UBOOT_ENTRYPOINT = "0x62000000"
UBOOT_LOADADDRESS = "0x62000000"
UBOOT_ENV_SIZE = "0x20000"

MACHINEOVERRIDES =. "mpuall:sama7g54_curiosity_pro:"
