header:
  version: 20

local_conf_header:
  dm-verity: |
    DISTRO_FEATURES:append = " mchp-dm-verity"
    DM_VERITY_IMAGE ?= "mchp-base-image"

  mchp-auth: |
    DISTRO_FEATURES:append = " mchp-auth"
    # Set MCHP_DEV_SIGNING_KEYS to "0" when using production signing keys.
    # Provide FIT signing keys in UBOOT_SIGN_KEYDIR.
    # For mpfs and pic64 machines, provide HSS signing keys in HSS_SIGN_KEYDIR.
    MCHP_DEV_SIGNING_KEYS = "1"

repos:
  meta-security:
    path: layers/meta-security
    url: https://git.yoctoproject.org/meta-security.git
    commit: c0d1d6200e7a84c39fb940cb1f22aad4b0b3d808  # wrynose
    layers:
      .:
