DISTRO = "mchp-distro"
DISTRO_NAME = "Microchip Distro"
DISTRO_VERSION = "1.0"

DISTROOVERRIDES = "${DISTRO}"
TARGET_VENDOR = "-mchp"
SDK_VENDOR = "-mchpsdk"
SDK_VERSION = "${DISTRO_VERSION}"

MAINTAINER = "\
		Valentina Fernandez <valentina.fernandezalanis@microchip.com> \
		Nicolas Ferre <nicolas.ferre@microchip.com> \
		Dharma Balasubiramani <dharma.b@microchip.com> \
		"

MCHP_INIT_MANAGER ?= "systemd"
PACKAGE_CLASSES ?= "package_ipk"

MCHP_DEFAULT_DISTRO_FEATURES = ""
DISTRO_FEATURES ?= "${MCHP_DEFAULT_DISTRO_FEATURES}"

INIT_MANAGER ?= "${MCHP_INIT_MANAGER}"

DISTROOVERRIDES:append = "${@bb.utils.contains('DISTRO_FEATURES', 'mchp-dm-verity', ':mchp-dm-verity', '', d)}"
require ${@bb.utils.contains('DISTRO_FEATURES', 'mchp-dm-verity', 'include/mchp-dm-verity.inc', '', d)}
